### ISSUE TITLE
error/typo in images/syllable.png

### ISSUE THREAD

**Issue by nbuwe** [w3c/tlreq#13]
`images/syllable.png` (at https://w3c.github.io/tlreq/#syllable_structure in the text) says that _ya_, _ra_, _la_, ___sa___ are the subscribed letters.  _sa_ is listed there by mistake.  cf e.g. `images/subscripts.png`.

Probably, it's _wa_ that was meant here instead - though I'm not prepared to argue whether _wa zur_ should be considered a proper subjoined letter or, with _'a chung_, constitutes a separate class, neither am I properly familiar with the Tibetan tradition of formally analyzing its status.

**Comment by r12a** [comment]
Thanks for the comment.  I'm currently (slowly) rewriting that page, so i'll factor this in to that work.  It may take a while, but watch this space.
